#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event = 'nethvoice-wizard-ui-update';

event_actions($event, qw(
    initialize-default-databases 00
));

event_templates($event, qw(
    /var/www/html/freepbx/wizard/scripts/custom.js
    /var/www/html/freepbx/wizard/scripts/macVendors.js
    /var/www/html/freepbx/wizard/styles/brand.css
));
